version: '3.2'
services:
  app:
    image: grey87/coplay-server
    volumes: ['./', '/usr/src/app']
    ports: [5000]
  mongo:
    image: mongo:3.0.15
    volumes: ['/data/db', '/data/db']
  redis:
    image: redis:3.2.9