version: '3.2'
services:
  server:
    image: grey87/coplay-server
#    build: .
    volumes:
      - /Users/sergey/projects/CoPlay-server:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongo
    networks:
      - backend
  mongo:
    image: mongo:3.4.6
#    volumes:
#      - /data/db:/data/db
    networks:
      - backend
  redis:
    image: redis:4.0.1-alpine
    networks:
      - backend
networks:
  backend:
